config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  resource :profile, only: [:show, :edit, :update, :destroy] do
    get :logout, on: :member
  end

  resources :publications, only: [:create]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  # Abre uma pagina com o email enviado
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root "home#index"

end

app/models/amigo.rb
class Amigo < ApplicationRecord
    belongs_to :user
    belongs_to :amigo, class_name: "User" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/colaborador.rb
class Colaborador < ApplicationRecord
    belongs_to :user
    belongs_to :publication
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user

  has_many :colaboradores
  has_many :colaboradores_users, through: :colaboradores, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  validates :nome, presence: true
  
  has_many :publications

  has_many :amigos
  has_many :amigos_users, through: :amigos, source: :amigo

  has_many :colaboradores
  has_many :colaboradores_publications, through: :colaboradores, source: :publication
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @publication = current_user.publications.build
    else
      @user = User.new
    end

    @publications = Publication.order(created_at: :desc)

  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!

    before_action :update_resource_params, only: [:update]

    def show
        @user = current_user
      end
    
      def edit
        @user = current_user
      end

      def update
        @user = current_user
        if @user.update_with_password(update_resource_params)
          bypass_sign_in(@user) if update_resource_params[:password].present?
          redirect_to profile_path, notice: "Perfil atualizado com sucesso."
        else
          redirect_to profile_path, notice: "Erro ao atualizar."
        end
      end
    
      def destroy
        @user = current_user
        @user.destroy
        redirect_to root_path, notice: "Conta excluída com sucesso."
      end

      def logout
        sign_out(current_user)
        redirect_to root_path, notice: "Você saiu da sua conta."
      end
    
      private

      def confirmation_enabled?
        devise_mapping.confirmable?
      end
      helper_method :confirmation_enabled?

      def update_resource_params
        params.require(:user).permit(:nome, :email, :password, :password_confirmation, :current_password)
      end

end

app/controllers/publicationsController.rb
class PublicationsController < ApplicationController
    def create
      @publication = current_user.publications.build(publication_params)
      if @publication.save
        redirect_to root_path, notice: "Publicação criada com sucesso."
      else
        render "home/index"
      end
    end
  
    private
  
    def publication_params
      params.require(:publication).permit(:titulo, :descricao, :link)
    end
  end
  

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :email, :password, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nome, :email, :password, :password_confirmation])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def current_ability
    @current_ability ||= Ability.new(current_user)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/_amigos.html.erb
    <div class="card amigos" >
        <div class="card-header">
            Amigos
        </div>
        <div class="card-body p-0">
            <ul class="list-group  rounded-0 rounded-bottom">
                <li class="list-group-item border-0 border-top">Amigo 1</li>
                <li class="list-group-item border-0 border-top">Amigo 2</li>
                <li class="list-group-item border-0 border-top">Amigo 3</li>
                <li class="list-group-item border-0 border-top">Amigo 4</li>
                <li class="list-group-item border-0 border-top">Amigo 5</li>
            </ul>
        </div>
    </div>

app/views/home/_post.html.erb
<% publications.each do |publication| %>
  <div class="card mb-3" style="height:500px;">
      <%#   HEAD  %>
    <div class="card-header d-flex">
      <div title="Nome da pessoa" class="bg-body-secondary rounded-5 ms-1" style="width:24px; height:24px;"></div>
      
      <span class="me-3 ms-2" ><%=publication.user.nome%></span>
      
      <span class="" >selo</span>
      
    </div>
    
    <div class="card-body d-flex">
      <%#   FOTO  %>
      <div class="foto col-6 h-100 border rounded">
      teste
      </div>
      <%#   DESCRIAÇÃO  %>
      <div class="descricao col-6 h-100  px-2">
          <h5 class="card-title"><%=publication.titulo%></h5>
          <p class="card-text"><%=publication.descricao%></p>
          <p>Link: <%= publication.link%></p>
          
      </div>
    </div>
    <%#   FOOTER  %>
    <div class="card-footer text-body-secondary d-flex align-items-center">
      <span calss="me-1">Colaboradores:</span>
      <div class="d-flex">
          <div title="Nome da pessoa" class="bg-body-secondary rounded-5 ms-1" style="width:24px; height:24px;"></div>
          <div title="Nome da pessoa" class="bg-body-secondary rounded-5 ms-1" style="width:24px; height:24px;"></div>
      </div>
    </div>
  </div>
<%end%>

app/views/home/index.html.erb
<div class="contents col-12 h-100 d-flex">
    <div class="col-1"></div>
    <div class="feed col-7 me-5" >
        <% if user_signed_in? %>
            <div class="card mb-2">
                <div class="card-header ">
                    Mostre seu trabalho!
                </div>
                <div class="card-body">
                    
                        <%= form_for @publication, url: publications_path do |f| %>
                            <div class="field ">
                                <%= f.label :titulo %>
                                <%= f.text_field :titulo, class:"form-control" %>
                            </div>

                            <div class="field ">
                                <%= f.label :descricao %>
                                <%= f.text_area :descricao, class:"form-control" %>
                            </div>
                            <div class="field ">
                                <%= f.label :link %>
                                <%= f.text_field :link, class:"form-control" %>
                            </div>
                            
                            <%= f.submit "Criar Publicação", class:"btn btn-primary mt-2" %>
                        <% end %>
                    
                </div>
            </div>
        <% end %>
        <%= render partial: "home/post", locals: {publications: @publications}%>
    </div>
    
    <div class="right-area col-3 position-fixed" style="right:50px;">
        <% unless user_signed_in? %>
            <%= render partial: "users/sessions/form_session", locals: { newUserSession: @user }%>
        <%else%>    
            <%= render partial: "home/amigos"%>
        <%end%>
    </div>
    
</div>

app/views/layouts/_naveBar.html.erb
<nav class="navbar bg-body-tertiary fixed-top">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">
    <%= link_to "Editora livre", root_path, class: "navbar-brand" %></span>
    <div class="d-flex align-items-center">
      
      <% if user_signed_in? %>
        
        <% if current_user.verificado %>
          <span class="" >selo</span>
        <% end %>
        
        <span class="me-3 ms-2" ><%=current_user.nome%></span>
        <%= link_to profile_path do %>
          <%= content_tag(:div,"" ,class:"rounded-5 bg-secondary-subtle",style:"width:40px; height:40px;" ) %>
        <%end%>
        
      <% else%>
        <div class="rounded-5 bg-secondary-subtle" style="width:40px; height:40px;"></div>
      <%end%>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EditoraLivre</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: "layouts/naveBar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/profiles/_formEdit.html.erb
<%= form_for @user, url: profile_path, method: :put do |f| %>
  
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <% if @user.respond_to?(:unconfirmed_email) && @user.unconfirmed_email.present? %>
    <div>Currently waiting confirmation for: <%= @user.unconfirmed_email %></div>
  <% end %>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "current-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar alterações" %>
  </div>
<% end %>

app/views/profiles/_publi.html.erb
<div class="card mb-3" style="height:500px;">
    <%#   HEAD  %>
  <div class="card-header d-flex">
    <div title="Nome da pessoa" class="bg-body-secondary rounded-5 ms-1" style="width:24px; height:24px;"></div>
    
    <span class="me-3 ms-2" >nome</span>
    
    <span class="" >selo</span>
    
  </div>
  
  <div class="card-body d-flex">
    <%#   FOTO  %>
    <div class="foto col-6 h-100 border rounded">
    teste
    </div>
    <%#   DESCRIAÇÃO  %>
    <div class="descricao col-6 h-100  px-2">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        
    </div>
  </div>
  <%#   FOOTER  %>
  <div class="card-footer text-body-secondary d-flex align-items-center">
    <span calss="me-1">Colaboradores:</span>
    <div class="d-flex">
        <div title="Nome da pessoa" class="bg-body-secondary rounded-5 ms-1" style="width:24px; height:24px;"></div>
        <div title="Nome da pessoa" class="bg-body-secondary rounded-5 ms-1" style="width:24px; height:24px;"></div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="content d-flex">
    <div class="col-1"></div>
    <div class="col-2 me-5">
        <ul class="nav nav-pills mb-3 d-flex flex-column" id="pills-tab" role="tablist">
            <li class="nav-item mb-2 " role="presentation">
                <button class="nav-link btn col-12 border rounded active" id="pills-my-publi-tab" data-bs-toggle="pill" data-bs-target="#pills-my-publi" type="button" role="tab" aria-controls="pills-my-publi" aria-selected="true">Minhas publicações</button>
            </li>
            <li class="nav-item mb-2 " role="presentation">
                <button class="nav-link btn col-12 border rounded" id="pills-amigos-tab" data-bs-toggle="pill" data-bs-target="#pills-amigos" type="button" role="tab" aria-controls="pills-amigos" aria-selected="false">Amigos</button>
            </li>
            <li class="nav-item mb-2 " role="presentation">
                <button class="nav-link btn col-12 border rounded" id="pills-edit-tab" data-bs-toggle="pill" data-bs-target="#pills-edit" type="button" role="tab" aria-controls="pills-edit" aria-selected="false">Editar conta</button>
            </li>
            <li class="nav-item mb-2 " role="presentation">
                <button class="nav-link btn col-12 border rounded" id="pills-verificado-tab" data-bs-toggle="pill" data-bs-target="#pills-verificado" type="button" role="tab" aria-controls="pills-verificado" aria-selected="false">Verificado</button>
            </li>
            <li class="nav-item mb-2 ">
                <%= link_to "Excluir Conta", registration_path(current_user), method: :delete, data: { confirm: "Tem certeza que deseja excluir sua conta?" }, class: "btn col-12 btn-outline-danger" %>
            </li>
            <li class="nav-item mb-2 ">
                <%= link_to "Sair",  logout_profile_path , class: "btn btn-outline-primary col-12" %>
            </li>
            
        </ul>
    </div>

    <div class="tab-content col-6" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-my-publi" role="tabpanel" aria-labelledby="pills-my-publi-tab" tabindex="0">
            <div class="feed-my-publi">
                <% @user.publications.each do |publication| %>
                    
                    <div class="card mb-3" style="height:500px;">
                            <%#   HEAD  %>
                        <div class="card-header d-flex">
                            <div title="Nome da pessoa" class="bg-body-secondary rounded-5 ms-1" style="width:24px; height:24px;"></div>
                            
                            <span class="me-3 ms-2" ><%=current_user.nome%></span>
                            
                            <span class="" >selo</span>
                            
                        </div>
                        
                        <div class="card-body d-flex">
                            <%#   FOTO  %>
                            <div class="foto col-6 h-100 border rounded">
                            teste
                            </div>
                            <%#   DESCRIAÇÃO  %>
                            <div class="descricao col-6 h-100  px-2">
                                <h5 class="card-title"><%=publication.titulo%></h5>
                                <p class="card-text"><%=publication.descricao%></p>
                                
                            </div>
                        </div>
                        <%#   FOOTER  %>
                        <div class="card-footer text-body-secondary d-flex align-items-center">
                            <span calss="me-1">Colaboradores:</span>
                            <div class="d-flex">
                                <div title="Nome da pessoa" class="bg-body-secondary rounded-5 ms-1" style="width:24px; height:24px;"></div>
                                <div title="Nome da pessoa" class="bg-body-secondary rounded-5 ms-1" style="width:24px; height:24px;"></div>
                            </div>
                        </div>
                    </div>


                <% end %>
            </div>      
        </div>
        <div class="tab-pane fade" id="pills-amigos" role="tabpanel" aria-labelledby="pills-amigos-tab" tabindex="0">
            
            <%# AMIGOS DO USUARIO %>

            <%= render partial: "home/amigos"%>

        </div>
        <div class="tab-pane fade" id="pills-edit" role="tabpanel" aria-labelledby="pills-edit-tab" tabindex="0">
            <%= render "formEdit"%>
        </div>
        <div class="tab-pane fade" id="pills-verificado" role="tabpanel" aria-labelledby="pills-verificado-tab" tabindex="0">
            <div class="card">
                <h5 class="card-header">Featured</h5>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>  
        </div>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>